//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class alibabaEntities : DbContext
    {
        public alibabaEntities()
            : base("name=alibabaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bus> Bus { get; set; }
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<Company> Company { get; set; }
        public virtual DbSet<Country> Country { get; set; }
        public virtual DbSet<Facility> Facility { get; set; }
        public virtual DbSet<Flight> Flight { get; set; }
        public virtual DbSet<Foreign> Foreign { get; set; }
        public virtual DbSet<Hotel> Hotel { get; set; }
        public virtual DbSet<HotelOrder> HotelOrder { get; set; }
        public virtual DbSet<Internal> Internal { get; set; }
        public virtual DbSet<Room> Room { get; set; }
        public virtual DbSet<Ticket> Ticket { get; set; }
        public virtual DbSet<Transaction> Transaction { get; set; }
        public virtual DbSet<Trip> Trip { get; set; }
        public virtual DbSet<TripTicket> TripTicket { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<UsersWithNonZeroBalance> UsersWithNonZeroBalance { get; set; }
    }
}
