//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bus
    {
        public int bus_id { get; set; }
        public string bus_type { get; set; }
        public string departure_terminal { get; set; }
        public string destination_terminal { get; set; }
        public int trip_id { get; set; }
    
        public virtual Trip Trip { get; set; }
    }
}
