//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Internal
    {
        public int internal_id { get; set; }
        public int terminal { get; set; }
        public bool is_available { get; set; }
        public string special_offer { get; set; }
        public int flight_id { get; set; }
    
        public virtual Flight Flight { get; set; }
    }
}
